### ISSUE TITLE
User data read-only?

### ISSUE THREAD

**Issue by mariomadproductions** [flathub/io.github.Arisotura.CoinKiller#14]
It seems to mount it under `/var/lib/flatpak/app/io.github.Arisotura.CoinKiller/current/active/files/bin/coinkiller_data`, which is read-only. So updating the sprite data fails, as does saving settings like the RomFS folder. This is on Linux Mint 20.3, with that flatpak installed via the Software Manager.

**Comment by mariomadproductions** [comment]
Strange. What distro are you using?

This is how it is on my PC:
```
$ cd /var/lib/flatpak/app/io.github.Arisotura.CoinKiller/current/active/files/bin/coinkiller_data
$ ls
backgrounds         entrancetypes.txt  spritecategories.xml  tileoverlays
blank_course.bin    icons              spritedata.xml        tileoverrides
blank_level.sarc    languages          sprites               tilesetnames.txt
blank_tileset.sarc  levelnames.txt     tilebehaviors.xml     worldnames.txt
entrances           musicids.txt       tilecollisions
$ touch test
touch: cannot touch 'test': Permission denied
$ sudo touch test
[sudo] password for user:         
$ sudo rm test
$ cd ~/.var/app/io.github.Arisotura.CoinKiller/data/
$ ls
$ touch test
$ rm test
```

**Comment by JakobDev** [comment]
Why did you want to write to `/var/lib/flatpak/app/io.github.Arisotura.CoinKiller/current/active/files/bin/coinkiller_data`? You should not need to do this.

**Comment by mariomadproductions** [comment]
> Why did you want to write to `/var/lib/flatpak/app/io.github.Arisotura.CoinKiller/current/active/files/bin/coinkiller_data`? You should not need to do this.

Ah, so this is just where the default files are stored? I'm not sure why CoinKiller is not writing to `~/.var/app/io.github.Arisotura.CoinKiller/data/` then.

**Comment by JakobDev** [comment]
Could you link to a documentation that describe what you are trying to do?

**Comment by mariomadproductions** [comment]
> Could you link to a documentation that describe what you are trying to do?

I don't think there is any, but I'm trying to update the sprite data, and save the RomFS folder. Just normal CoinKiller functions.

**Comment by JakobDev** [comment]
All data you edit from the RomFS folder should be saved in the RomFS directory and nowhere else

**Comment by mariomadproductions** [comment]
> All data you edit from the RomFS folder should be saved in the RomFS directory and nowhere else

Normally, CoinKiller will save the last-opened folder, and be able to update spritedata from the online database. That functionality doesn't appear to be working.

**Comment by mariomadproductions** [comment]
> > Normally, CoinKiller will save the last-opened folder
> 
> It works for me. Did you have Settings>Load last ROMFS checked?

Whoops, I didn't. Working now that I've checked that box.

> 
> > be able to update spritedata from the online database
> 
> [I have created a Issue upstream for this](https://github.com/Arisotura/CoinKiller/issues/71)

Ah I see, its not something on my end then. Thanks.
